await loadScript("https://cdn.statically.io/gl/metagrowing/extra-shaders-for-hydra/main/lib/lib-screen.js")

osc(1, 1, 1)
	.diff(src(o0)
		.mask(shape([99, 4, 3], .9)
			// 			.scale([1.699, .5].smooth())
		)
	)
	.out();
src(o0)
	.sobelx()
	.out(o1)
src(o2)
	.diff(src(o1)
		.scrollX(.1, 3)
		.rotate(.1, 1))
	.scale([1.1].smooth())
// 	.modulateScale(noise(1), .2)
// 	.modulateRotate(noise(1), .2)
	.out(o2)
render(o2)