[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
    from = "/hydra-extras.js"
    status = 301
    force = false
    to = "https://gitlab.com/emptyflash/extra-shaders-for-hydra/-/raw/main/lib/all.js"
