version: '3'
services:
    watchcat:
        build: .
        volumes:
            - ${SHADER_FOLDER}:/home/app/shader

    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf

    caddy:
        image: emptyflash/caddy
        environment:
            - ACME_AGREE=true
            - NAMECOM_USERNAME=${NAMECOM_USERNAME}
            - NAMECOM_API_TOKEN=${NAMECOM_API_TOKEN}
        volumes:
            - ./Caddyfile:/etc/Caddyfile
            - ${HOME}/.caddy:/root/.caddy
            - ./index.html:/srv/index.html
            - ./std.frag:/srv/std.frag
        ports:
            - "2015:2015"
            - "4443:443"

    ngrok:
        image: wernight/ngrok
        command: ["ngrok", "http", 
            "-hostname", "local.cameron.pizza",
            "--log", "stdout",
            "--authtoken", "${NGROK_AUTHTOKEN}",
            "caddy:80"
        ]
        ports:
            - "4040:4040"
