version: '3'
services:
    watchcat:
        build: .
        volumes:
            - ${SHADER_FOLDER}:/shader
            - "~/Projects/yinlang/std.yin:/std.yin"
            - "./watchcat.sh:/watchcat.sh"
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - watchcat
    ngrok:
        image: wernight/ngrok
        command: ["ngrok", "http", 
            "-hostname", "local.cameron.pizza",
            "--log", "stdout",
            "--authtoken", "${NGROK_AUTHTOKEN}",
            "nginx:80"
        ]
        depends_on:
            - nginx
